name: Deploy to S3

on:
  push:
    branches: ["main"]

env: 
  AWS_REGION: ap-southeast-1
  S3_BUCKET_NAME: zhbucket123     #avoid hard coding

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Scan repo with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

    - name: Upload files to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --acl public-read






